# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.xci
# IP: The module: 'ip_mmcm_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.xci
# IP: The module: 'ip_mmcm_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_mmcm_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
