# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/l2425/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-28544-DESKTOP-ELTC2F5/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.cache/wt [current_project]
set_property parent.project_path E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  D:/home/qaq/e203/e203_hbirdv2/fpga/install/rtl/core
  D:/home/qaq/e203/e203_hbirdv2/fpga/install/rtl/perips/apb_i2c
  D:/home/qaq/e203/e203_hbirdv2/fpga/install/rtl
  D:/home/qaq/e203/e203_hbirdv2/fpga/install/rtl/perips
} [current_fileset]
read_ip -quiet e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.xci
set_property used_in_implementation false [get_files -all e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1 -new_name ip_mmcm_clk_wiz_0_1 -ip [get_ips ip_mmcm_clk_wiz_0_1]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top ip_mmcm_clk_wiz_0_1 -part xc7z010clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix ip_mmcm_clk_wiz_0_1_ ip_mmcm_clk_wiz_0_1.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ip_mmcm_clk_wiz_0_1_stub.v
 lappend ipCachedFiles ip_mmcm_clk_wiz_0_1_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ip_mmcm_clk_wiz_0_1_stub.vhdl
 lappend ipCachedFiles ip_mmcm_clk_wiz_0_1_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ip_mmcm_clk_wiz_0_1_sim_netlist.v
 lappend ipCachedFiles ip_mmcm_clk_wiz_0_1_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ip_mmcm_clk_wiz_0_1_sim_netlist.vhdl
 lappend ipCachedFiles ip_mmcm_clk_wiz_0_1_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp ip_mmcm_clk_wiz_0_1.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips ip_mmcm_clk_wiz_0_1]
}

rename_ref -prefix_all ip_mmcm_clk_wiz_0_1_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ip_mmcm_clk_wiz_0_1.dcp
create_report "ip_mmcm_clk_wiz_0_1_synth_1_synth_report_utilization_0" "report_utilization -file ip_mmcm_clk_wiz_0_1_utilization_synth.rpt -pb ip_mmcm_clk_wiz_0_1_utilization_synth.pb"

if { [catch {
  file copy -force E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1/ip_mmcm_clk_wiz_0_1.dcp e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1/ip_mmcm_clk_wiz_0_1.dcp e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1/ip_mmcm_clk_wiz_0_1_stub.v e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1/ip_mmcm_clk_wiz_0_1_stub.vhdl e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1/ip_mmcm_clk_wiz_0_1_sim_netlist.v e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.runs/ip_mmcm_clk_wiz_0_1_synth_1/ip_mmcm_clk_wiz_0_1_sim_netlist.vhdl e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.ip_user_files/ip/ip_mmcm_clk_wiz_0_1]} {
  catch { 
    file copy -force e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_stub.v E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.ip_user_files/ip/ip_mmcm_clk_wiz_0_1
  }
}

if {[file isdir E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.ip_user_files/ip/ip_mmcm_clk_wiz_0_1]} {
  catch { 
    file copy -force e:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.srcs/sources_1/bd/ip_mmcm/ip/ip_mmcm_clk_wiz_0_1/ip_mmcm_clk_wiz_0_1_stub.vhdl E:/files/A0_fpga_learn/ZYNQ_7010_FPGA/e203_7010/e203_7010.ip_user_files/ip/ip_mmcm_clk_wiz_0_1
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
